[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "base-uri 'self'; default-src 'self' https://www.youtube.com/ https://fonts.gstatic.com ws://localhost:1313/livereload; img-src * 'self' data: https: http:; script-src 'self' 'unsafe-inline' https://api.reftagger.com https://static.cloudflareinsights.com https://ajax.cloudflare.com https://ajax.googleapis.com; style-src  'self' 'unsafe-inline' https://fonts.googleapis.com; object-src 'none'; frame-ancestors 'none';" always;
    X-UA-Compatible = "IE=Edge";
    X-Content-Type-Options = "nosniff" always;  
    X-Frame-Options = SAMEORIGIN always;  
    X-XSS-Protection = "1; mode=block" always; 

